("python38Packages.python-slugify" "prboom" "zandronum" "nethogs" "zdbsp"
 "timidity" "teams" "doomseeker" "pdflatex" "texlive.combined.scheme-minimal"
 "trenchboom" "unityhub" "slade3" "espeak" "festival" "livesplit" "urn-timer"
 "slade" "pkg-config" "sabaki" "git-cola" "gitk" "picocad" "tweet-hs"
 "python38Packages.rainbowstream" "wineWowPackages.stable" "qmk_firmware"
 "runescape-launcher" "vmware-horizons" "darcs" "ue5" "maven"
 "dotnetCorePackages.sdk_4_7" "dotnetCorePackages.sdk_5_0"
 "python39Packages.aioinflux" "influxdb" "dotnet-sdk" "dotnetPackages.Nuget"
 "mono4" "dotnet-sdk_5" "msbuild" "haskellPackages.zlib" "pkgconfig" "spectral"
 "dos2unix" "aria2c" "haskellPackages.cabal-install" "vlc"
 "haskellPackages.ghc" "python38Packages.lens"
 "python38Packages.accumulation-tree" "element-desktop" "uzbl" "connect"
 "pass-import" "python38Packages.python-magic" "python38Packages.magic" "piper"
 "wxcam" "ansible" "python3.7" "mbox" "python37\"" "python37" "pytype"
 "python3Packages.pygame" "plan9port" "fluidsynth" "ninja"
 "python38Packages.ninja" "dolphin" "dolphin-emu" "dolphinEmu" "clojure"
 "webex" "sqlmap" "browsh" "zlib-dev" "zlib.dev" "zlib" "zlib.out" "libcurl"
 "curl.dev" "vorbisTools" "pssst" "psst" "dbus_tools" "xsensors" "lm_sensors"
 "openxray" "valgrind" "ue4" "chromedriver" "darkplaces" "rustc" "godot"
 "protontricks" "winecfg" "gcc-unwrapped" "windows" "musl" "shfmt" "crispyDoom"
 "google-chrome" "armagetron" "gzdoom" "geeqie" "bsidff" "bsdiff" "yuzu-ea"
 "nodejs-12_x" "python310" "vmware-view" "vmware-horizon-client" "elixir"
 "arduino" "cinnamon.nemo" "vscode" "openjdk16" "hpack"
 "rustup-toolchain-install-master" "rustfmt" "haskell-language-server"
 "haskell.packages.ghc921.haskell-language-server" "telegram" "tdeskop"
 "openjdk17" "drive" "rstudio" "cawbird" "franz" "snowmachine" "armagetronad"
 "anki" "fbreadder" "fbreader" "minify" "trickle" "mesen" "nestopia"
 "retroarchFull" "luaPackages.luasocket" "lua51Packages.luasockett" "lua51"
 "lua51Packages.lu" "lua51Packages.lua" "elm2nix"
 "lua51Packages.lua-messagepack" "lua51Packages.lua-yajl" "cargo"
 "lua51Packages.luasockets" "lua51Packages.lua-sockets"
 "lua51Packages.luasocket" "fceux-unstable" "ghc92" "menyoki"
 "haskell.compiler.ghc921" "haskell.compiler.ghc901" "haskell.compiler.ghc902"
 "aseprite-unfree" "influxdb-client" "python39Packages.influxdb-client"
 "chiaki" "opentelemetry-collector" "protobuf" "pony-corral" "nyxt" "certbot"
 "acme-client" "emacsGit" "zoom-u" "arduino-cli" "terminator" "mastodon-bot"
 "gprolog" "trealla" "swiProlog" "cmatrix" "Cutter" "minicom" "julia_17-bin"
 "(.+)'" "libusb1" "bwrap" "ponyup" "nixos-option" "buku" "cargo2nix"
 "ghidra-bin" "python310Packages.pwntools" "qdirstat" "leetcode-cli" "kdenlvie"
 "raku" "rakudo" "puredata" "ngrok" "twint" "haskellPackages.tweet-hs" "cutter"
 "wxhexeditor" "bpftrace" "figlet" "sunvox" "dex2jar" "cfr" "jd-gui" "jadx"
 "binwalk" "kaldi" "dragonfly" "python39Packages.dragonfly"
 "discord.updateScript" "zoom-us" "dnsutils.dnsutils" "konsole" "libseccomp"
 "gource" "xivlauncher" "gensgs" "kega-fusion" "dgen-sdl" "ruby" "elm"
 "elmPackages.elm" "elmPackages.elm-format" "imhex" "glxgears" "glxinfo"
 "oneko" "kdenlive" "jabref" "mgba" "stdenv.cc.cc.lib" "panda" "pandas"
 "python38Packages.pandas" "([^" "dolphin-emu-beta" "polychromatic" "lldb")
